# -*- coding: utf-8 -*-
"""rule based bot demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oohK1xEY37IQ_frjJXA7kVVIntboKWr5
"""

import re
import random

class RuleBot:
  ###Potential Negative Responses
  negative_responses = ("no", "nope", "nah", "naw", "not a chance", "sorry")
  ### Exit conversation Keywords
  exit_commands = ("quit", "pause", "exit", "goodbye", "bye", "later")
  ###Randaom starter questions
  random_questions = ("why are you here?",
                      "are there many humans like you?",
                      "what do you consume for sustenance?",
                      "is there intelligent life on this planet?",
                      "does earth have a leader?",
                      "what planets have you visited?")
  def __init__(self):
    self.alienbabble = {'describe_planet_intent': r'.*\s*your\s*planet.*',
                       'answer_why_intent': r'why\sare.*',
                       'about_intellipat': r'.*\s*intellipa'
    }
  def greet(self):
    self.name=input("What is your name?\n")
    will_help = input(f"Hi {self.name}, I am Rule-Bot. Will you help me learn about your planet?\n")
    if will_help in self.negative_responses:
      print("Ok, have a nice Earth day!")
      return
    self.chat()
  def make_exit(self, reply):
    for command in self.exit_commands:
      if reply == command:
        print("Okay, have a nice Earth day!")
        return True
  def chat(self):
    reply = input(random.choice(self.random_questions)).lower()
    while not self.make_exit(reply):
      reply = input(self.match_reply(reply))
  def match_reply(self, reply):
    for key, value in self.alienbabble.items():
      intent = key
      regex_pattern = value
      found_match = re.match(regex_pattern, reply)
      if found_match and intent == 'describe_planet_intent':
        return self.describe_planet_intent()
      elif found_match and intent == 'answer_why_intent':
        return self.answer_why_intent()
      elif found_match and intent == 'about_intellipat':
        return self.about_intellipat()
    if not found_match:
      return self.no_match_intent()
  def describe_planet_intent(self):
    responses = ("My planet is a utopia of diverse organisms and species.\n",
                 "I am from Opidipus, the capital of the Wayward Galaxies.\n")
    return random.choice(responses)
  def answer_why_intent(self):
    responses = ("I come in peace\n", "I am here to collect data on your planet and its inhabitants\n",
                 "I heard the coffee is good\n")
    return random.choice(responses)
  def about_intellipat(self):
    responses = ("Intellipaat is world's largest professional educational company\n",
                 "Intellipaat will make you learn concepts in the way never left before\n")
    return random.choice(responses)
  def no_match_intent(self):
    responses = ("Please tell me more.\n", "Tell me more!\n", "Why do you say that?\n", "I see. Can you elaborate?\n",
                 "Interesting. Can you tell me more?\n", "I see. How do you think?\n", "Why?\n","how do you think I feel when you say that?\n")
    return random.choice(responses)
AlienBot = RuleBot()
AlienBot.greet()
AlienBot.chat()
AlienBot.describe_planet_intent()
AlienBot.answer_why_intent()
AlienBot.about_intellipat()
AlienBot.no_match_intent()